name: 'Branch exists'
description: 'Check if a branch exists, cross-repo'
author: 'Arundo Analytics'
inputs:
  repository:
    description: 'Which repository to check in (format: owner/repo)'
    required: true
    default: null
  branch:
    description: 'Which branch to check'
    required: true
    default: null
  token:
    description: 'Github token'
    required: true
    default: null
outputs:
  exists:
    description: 'If the branch exists'
runs:
  using: 'node12'
  main: 'dist/index.js'